import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  price: 0,
};

export const priceSlice = createSlice({
  name: "price",
  initialState,
  // The `` field lets us define reducers and generate associated actions
  reducers: {
    setPrice: (state, action) => {
      state.price = action.payload;
    },
 
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const { setPrice } = priceSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectprice = (state) => state.price.price;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default priceSlice.reducer;
